### ISSUE TITLE
Add ETHERSCAN_API_KEY to .env.example

### ISSUE THREAD

**Issue by scorpion9979** [hifi-finance/hifi#16]
Most of the yarn scripts fail unless `ETHERSCAN_API_KEY` was provided in `.env`.

**Comment by paulrberg** [comment]
Perhaps you are referring to the `.env.example` at the root of the repo, which indeed lacks an `ETHERSCAN_API_KEY` field. But all others have it. I'll close this since #17 will implicitly solve this.
