### ISSUE TITLE
[deployers] Modify `HifiPool` deployer script to track pool upon deployment

### ISSUE THREAD

**Issue by scorpion9979** [hifi-finance/hifi#35]
Modify `HifiPool` deployer script to call `HifiPoolRegistry.trackPool(pool)` as soon as the pool is deployed.
This is critical for the subgraph, as any pool events that may have been emitted before the pool was added to registry would not be captured during subgraph sync. This is outlined in The Graph docs:

> Note: A new data source will only process the calls and events for the block in which it was created and all following blocks, but will not process historical data, i.e., data that is contained in prior blocks.

**Comment by paulrberg** [comment]
Implemented via #48.
