### ISSUE TITLE
[flash-swap] Improve pair contract assertion logic

### ISSUE THREAD

**Issue by scorpion9979** [hifi-finance/hifi#37]
In `HifiFlashUniswapV2.sol`, there's [this line](https://github.com/hifi-finance/hifi/blob/main/packages/flash-swap/contracts/uniswap-v2/HifiFlashUniswapV2.sol#L112) asserting that the sender address is the pair contract that was initialized at the constructor. Having the pairs set at the constructor makes the flash swap contract very difficult to adapt to new listed collateral tokens. Instead, I would suggest initializing the constructor with the Uniswap V2 init hash and factory contract address (they would change depending on which chain and Uniswap clone is used). The pair contract address to be used in the assertion would then be computed from the collateral and underlying token addresses as follows:

```solidity
(address token0, address token1) = sortTokens(underlying, collateral);
address pair = address(uint(keccak256(abi.encodePacked(
  hex'ff',
  factory,
  keccak256(abi.encodePacked(token0, token1)),
  initCodeHash
))));
```

This might be more costly in terms of gas, but it's a lot more dynamic and doesn't require any maintenance.

**Comment by paulrberg** [comment]
Sounds like a good idea.

> This might be more costly in terms of gas, but it's a lot more dynamic and doesn't require any maintenance.

It would. But all in all, it would cost less gas than deploying a new flash swap contract for every other new collateral listing.
